version: "3.9"

services:
  client_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app_client
    restart: always
    environment:
      NEXT_PUBLIC_WEB_API_URL: http://localhost:3050/api/v1
      NEXTAUTH_SECRET: secret_strong_1234_PGBPZP5AS9HVCDSPT7Y2NMSWP4NA4NSLC
  web_api:
    image: webbylabhub/movies
    container_name: movies-webbylab-web-api
    volumes:
      - movies_mysql:/var/lib/mysql
    ports:
      - 3050:3050
    environment:
      - PORT=3050

volumes:
  movies_mysql:
